# Generated by Django 3.1.7 on 2021-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210330_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phoneno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
